services:
  # 1. The Database Service
  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    ports:
      - "5000:5432"
    volumes:
      - ./user-service/db_volumes/user-service-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: momo
      POSTGRES_PASSWORD: momo
      POSTGRES_DB: db
    networks:
      - internal

  # 2. The Billing Service
  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "4001:4001" # REST port
      - "9001:9001" # gRPC port
    networks:
      - internal

  # 3. The User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: momo
      SPRING_DATASOURCE_PASSWORD: momo
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    depends_on:
      - user-service-db
      - billing-service
    networks:
      - internal

# 4. The Network Definition
networks:
  internal:
    driver: bridge