### Creates a new user entity
POST http://localhost:4000/users
Content-Type: application/json

{
  "username": "Momo after analytics-service",
  "email": "analytics-service@example.com",
  "password": "momo",
  "registeredDate": "2025-07-06"
}

###