### Creates a new user entity
POST http://localhost:4000/users
Content-Type: application/json

{
  "username": "Momo",
  "email": "Momo1222@example.com",
  "password": "momo",
  "registeredDate": "2025-07-06"
}

###