### Updates an existing user entity
PUT http://localhost:4000/users/6d746b6c-bec0-4afe-a539-1ad346372d2c
Content-Type: application/json

{
  "username": "Mohammad",
  "email": "momo@example.com"
}

###