### Updates an existing user entity
PUT http://localhost:4000/users/f30acc35-9927-40e7-9292-f00946da3b57
Content-Type: application/json

{
  "username": "Momo2",
  "email": "momo22@example.com"
}

###